[build]
  command = "npm run build"
  publish = "dist"
 base = “service” 

[template]
  incoming-hooks = ["OpenAI"]
  [template.environment]
    OPENAI_API_KEY = "your_api_key"
    OPENAI_ACCESS_TOKEN = "your_access_token"
    API_REVERSE_PROXY = "https://bypass.churchless.tech/api/conversation"

[context.production]
  environment = { NODE_ENV = "production" }
  [[context.production.redirects]]
    from = "/old-path"
    to = "/new-path"
    status = 301
    force = true
  [[context.production.headers]]
    for = "/*"
    [context.production.headers.values]
      X-Frame-Options = "DENY"
      X-XSS-Protection = "1; mode=block"
